FROM  debian:bullseye

RUN apt update && apt upgrade -y && apt install -y nginx iputils-ping && apt install openssl -y

# WORKDIR  /ssl

# COPY ./openssl.conf ./openssl.cnf
RUN chown -R www-data:www-data /var/www/html/
RUN chmod -R 755 /var/www/html/
# EXPOSE 443
# RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout private.key -out certificate.crt -config openssl.cnf

COPY ./nginx.conf  /etc/nginx/conf.d/default.conf

CMD ["nginx","-g","daemon off;"]